"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true

[git_branch]
ignore_branches = ['main', 'master']

[hostname]
format = "[$hostname]($style) "

[lua]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[username]
disabled = true
