- ansible.builtin.file:
    mode: "755"
    path: ~/.pulumi/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.pulumi/bin/pulumi
    dest: ~/.pulumi/bin
    extra_opts:
      - --strip-components=1
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://get.pulumi.com/releases/sdk/pulumi-v3.86.0-linux-{{ (arch.stdout == 'amd64') | ternary('x64', arch.stdout) }}.tar.gz
- ansible.builtin.file:
    mode: "755"
    path: ~/.temporalio/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.temporalio/bin/temporal
    dest: ~/.temporalio/bin
    extra_opts:
      - temporal
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://temporal.download/cli/archive/latest?platform=linux&arch={{ arch.stdout }}
- ansible.builtin.file:
    mode: "755"
    path: ~/.local/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.local/bin/bandwhich
    dest: ~/.local/bin
    remote_src: true
    src: https://github.com/imsnif/bandwhich/releases/download/v0.21.0/bandwhich-v0.21.0-x86_64-unknown-linux-musl.tar.gz
- ansible.builtin.git:
    dest: ~/thebengeu/neovim
    force: true
    repo: https://github.com/thebengeu/neovim
    version: 7ef1321d88a84cebf62a34cc2d79ebef91f74ea9
- ansible.builtin.command:
    chdir: ~/thebengeu/neovim
    cmd: make CMAKE_BUILD_TYPE=Release
    creates: ~/thebengeu/neovim/build/
- ansible.builtin.command:
    chdir: ~/thebengeu/neovim/build
    cmd: cpack -G DEB
    creates: ~/thebengeu/neovim/build/nvim-linux64.deb
- ansible.builtin.apt:
    deb: /home/{{ ansible_user_id }}/thebengeu/neovim/build/nvim-linux64.deb
  become: true
- community.general.alternatives:
    name: editor
    path: /usr/bin/nvim
  become: true
- ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: true
- ansible.builtin.get_url:
    dest: /tmp/rustup-init
    mode: "755"
    # yamllint disable-line rule:line-length
    url: https://static.rust-lang.org/rustup/dist/{{ ansible_machine }}-unknown-linux-gnu/rustup-init
- ansible.builtin.command:
    cmd: /tmp/rustup-init --no-modify-path --profile minimal -y
    creates: ~/.cargo/env
- ansible.builtin.command:
    cmd: nix profile install nixpkgs#{{ item }}
    creates: ~/.nix-profile/bin/{{ item }}
  loop:
    - direnv
    - fennel
    - hledger
    - hledger-ui
    - hledger-web
    - ledger
    - less
    - lf
    - miller
    - nethogs
    - nix
    - nnn
    - nushell
    - peco
    - vifm
- ansible.builtin.command:
    cmd: go install cuelang.org/go/cmd/cue@latest
    creates: ~/go/bin/cue
- ansible.builtin.command:
    cmd: cargo install {{ item }}
    creates: ~/.cargo/bin/{{ item }}
  environment:
    PATH: /usr/bin:/home/{{ ansible_user_id }}/.cargo/bin
  loop:
    - broot
    - just
    - starship
    - vivid
    - zoxide
