- ansible.builtin.file:
    mode: "755"
    path: ~/.pulumi/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.pulumi/bin/pulumi
    dest: ~/.pulumi/bin
    extra_opts:
      - --strip-components=1
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://get.pulumi.com/releases/sdk/pulumi-v3.86.0-linux-{{ (arch.stdout == 'amd64') | ternary('x64', arch.stdout) }}.tar.gz
- ansible.builtin.file:
    mode: "755"
    path: ~/.temporalio/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.temporalio/bin/temporal
    dest: ~/.temporalio/bin
    extra_opts:
      - temporal
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://temporal.download/cli/archive/latest?platform=linux&arch={{ arch.stdout }}
- ansible.builtin.git:
    dest: ~/thebengeu/neovim
    force: true
    repo: https://github.com/thebengeu/neovim
    version: ae24a26af43ce39541667d326b42142df247d8e7
- ansible.builtin.command:
    chdir: ~/thebengeu/neovim
    cmd: make CMAKE_BUILD_TYPE=Release
    creates: ~/thebengeu/neovim/build/
- ansible.builtin.command:
    chdir: ~/thebengeu/neovim/build
    cmd: cpack -G DEB
    creates: ~/thebengeu/neovim/build/nvim-linux64.deb
- ansible.builtin.apt:
    deb: /home/{{ ansible_user_id }}/thebengeu/neovim/build/nvim-linux64.deb
  become: true
- community.general.alternatives:
    name: editor
    path: /usr/bin/nvim
  become: true
- ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
  become: true
- ansible.builtin.get_url:
    dest: /tmp/rustup-init
    mode: "755"
    # yamllint disable-line rule:line-length
    url: https://static.rust-lang.org/rustup/dist/{{ ansible_machine }}-unknown-linux-gnu/rustup-init
- ansible.builtin.command:
    cmd: /tmp/rustup-init --no-modify-path --profile minimal -y
    creates: ~/.cargo/env
- ansible.builtin.command:
    cmd: go install cuelang.org/go/cmd/cue@latest
    creates: ~/go/bin/cue
- ansible.builtin.command:
    cmd: cargo install {{ item }}
    creates: ~/.cargo/bin/{{ item }}
  environment:
    PATH: /usr/bin:/home/{{ ansible_user_id }}/.cargo/bin
  loop:
    - broot
    - fnm
    - just
    - starship
    - vivid
    - zoxide
