- ansible.builtin.file:
    mode: "755"
    path: ~/.pulumi/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.pulumi/bin/pulumi
    dest: ~/.pulumi/bin
    extra_opts:
      - --strip-components=1
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://get.pulumi.com/releases/sdk/pulumi-v3.76.0-linux-{{ (arch.stdout == 'amd64') | ternary('x64', arch.stdout) }}.tar.gz
- ansible.builtin.file:
    mode: "755"
    path: ~/.temporalio/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.temporalio/bin/temporal
    dest: ~/.temporalio/bin
    extra_opts:
      - temporal
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://temporal.download/cli/archive/latest?platform=linux&arch={{ arch.stdout }}
- ansible.builtin.git:
    dest: ~/neovim
    force: true
    repo: https://github.com/neovim/neovim
    version: f2ce31d3dc1c728c33c0910e1a9970f0eb2e3f11
- ansible.builtin.command:
    chdir: ~/neovim
    cmd: make CMAKE_BUILD_TYPE=Release
    creates: ~/neovim/build/
- ansible.builtin.command:
    chdir: ~/neovim/build
    cmd: cpack -G DEB
    creates: ~/neovim/build/nvim-linux64.deb
- ansible.builtin.apt:
    deb: /home/{{ user }}/neovim/build/nvim-linux64.deb
  become: true
- community.general.alternatives:
    name: editor
    path: /usr/bin/nvim
  become: true
- ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"
    shell: /usr/bin/fish
  become: true
- ansible.builtin.get_url:
    dest: /tmp/rustup-init
    mode: "755"
    # yamllint disable-line rule:line-length
    url: https://static.rust-lang.org/rustup/dist/{{ ansible_machine }}-unknown-linux-gnu/rustup-init
- ansible.builtin.command:
    cmd: /tmp/rustup-init --no-modify-path --profile minimal -y
    creates: ~/.cargo/env
- community.general.cargo:
    name: broot
- community.general.cargo:
    name: cargo-update
- community.general.cargo:
    name: exa
- community.general.cargo:
    name: gitui
- community.general.cargo:
    name: just
- community.general.cargo:
    name: mcfly
- community.general.cargo:
    name: tealdeer
- community.general.cargo:
    name: tokei
- community.general.cargo:
    name: topgrade
- community.general.cargo:
    name: xh
- community.general.cargo:
    name: zoxide
- ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - skip_ansible_lint
- ansible.posix.authorized_key:
    key: https://github.com/thebengeu.keys
    user: "{{ user }}"
- ansible.builtin.command:
    cmd: chezmoi init --ssh thebengeu
    creates: ~/.local/share/chezmoi
- ansible.builtin.command:
    cmd: chezmoi apply --exclude templates
    creates: ~/.config/fish/fish_plugins
- ansible.builtin.get_url:
    dest: /tmp/fisher.fish
    mode: "644"
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
- ansible.builtin.shell:
    cmd: |
      source /tmp/fisher.fish
      fisher update
    creates: ~/.config/fish/functions/fisher.fish
    executable: /usr/bin/fish
- ansible.builtin.command:
    cmd: /usr/bin/bat cache --build
    creates: ~/.cache/bat/themes.bin
- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    creates: ~/.tmux/plugins/tmux-pain-control
- ansible.builtin.get_url:
    dest: ~/.local/bin/cht.sh
    mode: "755"
    url: https://cht.sh/:cht.sh
- ansible.builtin.command:
    cmd: nix profile install nixpkgs#peco
    creates: ~/.nix-profile/bin/peco
- ansible.builtin.command:
    cmd: go install github.com/nao1215/gup@latest
    creates: ~/go/bin/gup
- ansible.builtin.command:
    cmd: ~/go/bin/gup import
    creates: ~/go/bin/lazygit
- ansible.builtin.pip:
    name:
      - pipx
    extra_args: --user
- community.general.pipx:
    name: howdoi
- community.general.pipx:
    name: khal
- community.general.pipx:
    name: qmk
- community.general.pipx:
    name: sqlfluff
- community.general.yarn:
    name: npm-check-updates
    global: true
    production: true
- community.general.yarn:
    name: pino-pretty
    global: true
    production: true
- community.general.yarn:
    name: pm2
    global: true
    production: true
