- ansible.builtin.shell:
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    creates: ~/.config/fish/functions/fisher.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: yes | fisher install IlanCosman/tide@v5
    creates: ~/.config/fish/functions/tide.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: fisher install catppuccin/fish
    creates: ~/.config/fish/themes/Catppuccin Mocha.theme
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    creates: /home/linuxbrew
- community.general.homebrew:
    name:
      - bat
      - broot
      - btop
      - cantino/mcfly/mcfly
      - eth-p/software/bat-extras-batman
      - exa
      - fd
      - fnm
      - fzf
      - gh
      - ghorg
      - git-delta
      - gitui
      - lazydocker
      - lazygit
      - mosh
      - topgrade
      - wakatime-cli
      - xh
      - zoxide
- community.general.homebrew:
    install_options: HEAD
    name: neovim
- community.general.alternatives:
    name: editor
    path: /home/linuxbrew/.linuxbrew/bin/nvim
  become: yes
- ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: ~/nerd-fonts
- ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
- ansible.posix.authorized_key:
    key: https://github.com/thebengeu.keys
    user: "{{ user }}"
- community.general.pipx:
    name: ansible-lint
- community.general.pipx:
    name: tusker
- ansible.builtin.command:
    cmd: chezmoi init --apply --ssh thebengeu
    creates: ~/.local/share/chezmoi
- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    creates: ~/.tmux/plugins/tmux-pain-control
