- ansible.builtin.command:
    cmd: go install github.com/gabrie30/ghorg@latest
    creates: ~/go/bin/ghorg
- ansible.builtin.command:
    cmd: go install github.com/jesseduffield/lazydocker@latest
    creates: ~/go/bin/lazydocker
- ansible.builtin.command:
    cmd: go install github.com/jesseduffield/lazygit@latest
    creates: ~/go/bin/lazygit
- ansible.builtin.command:
    cmd: go install github.com/boyter/scc/v3@latest
    creates: ~/go/bin/scc
- ansible.builtin.file:
    mode: "755"
    path: ~/.pulumi/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.pulumi/bin/pulumi
    dest: ~/.pulumi/bin
    extra_opts: [--strip-components=1]
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://get.pulumi.com/releases/sdk/pulumi-v3.76.0-linux-{{ (arch.stdout == 'amd64') | ternary('x64', arch.stdout) }}.tar.gz
- ansible.builtin.file:
    mode: "755"
    path: ~/.temporalio/bin
    state: directory
- ansible.builtin.unarchive:
    creates: ~/.temporalio/bin/temporal
    dest: ~/.temporalio/bin
    extra_opts: [temporal]
    remote_src: true
    # yamllint disable-line rule:line-length
    src: https://temporal.download/cli/archive/latest?platform=linux&arch={{ arch.stdout }}
- ansible.builtin.git:
    dest: ~/neovim
    force: true
    repo: https://github.com/neovim/neovim
    version: f2ce31d3dc1c728c33c0910e1a9970f0eb2e3f11
- ansible.builtin.shell:
    chdir: ~/neovim
    cmd: |
      make CMAKE_BUILD_TYPE=Release &&
      cd build &&
      cpack -G DEB &&
      sudo dpkg -i nvim-linux64.deb
    creates: /usr/bin/nvim
- community.general.alternatives:
    name: editor
    path: /usr/bin/nvim
  become: true
- ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ user }}"
    shell: /usr/bin/fish
  become: true
- ansible.builtin.shell:
    # yamllint disable rule:line-length
    cmd: |
      set -o pipefail
      curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source &&
      fisher install jorgebucaran/fisher
    # yamllint enable rule:line-length
    creates: ~/.config/fish/functions/fisher.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: |
      set -o pipefail
      yes | fisher install IlanCosman/tide@v5
    creates: ~/.config/fish/functions/tide.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    # yamllint disable rule:line-length
    cmd: |
      set -o pipefail
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --profile minimal -y
    # yamllint enable rule:line-length
    creates: ~/.cargo/env
    executable: /usr/bin/fish
- community.general.cargo:
    name: broot
- community.general.cargo:
    name: cargo-update
- community.general.cargo:
    name: exa
- community.general.cargo:
    name: gitui
- community.general.cargo:
    name: mcfly
- community.general.cargo:
    name: topgrade
- community.general.cargo:
    name: xh
- community.general.cargo:
    name: zoxide
- ansible.builtin.shell:
    cmd: fisher install catppuccin/fish
    creates: ~/.config/fish/themes/Catppuccin Mocha.theme
    executable: /usr/bin/fish
- ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
  tags:
    - skip_ansible_lint
- ansible.posix.authorized_key:
    key: https://github.com/thebengeu.keys
    user: "{{ user }}"
- ansible.builtin.command:
    cmd: chezmoi init --ssh thebengeu
    creates: ~/.local/share/chezmoi
- ansible.builtin.command:
    cmd: chezmoi apply --exclude templates
    creates: ~/.tmux.conf
- ansible.builtin.command:
    cmd: /usr/bin/bat cache --build
    creates: /home/beng/.cache/bat/themes.bin
- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    creates: ~/.tmux/plugins/tmux-pain-control
