matches:
  - trigger: :bq
    replace: '%%bigquery'
  - trigger: :date
    replace: '{{mydate}}'
    vars:
      - name: mydate
        type: date
        params:
          format: '%F'
  - trigger: :dt
    replace: '{{datetime}}'
    vars:
      - name: datetime
        type: date
        params:
          format: '%F %R'
  - trigger: :time
    replace: '{{mytime}}'
    vars:
      - name: mytime
        type: date
        params:
          format: '%R'
