.tmux/plugins/tpm:
  type: git-repo
  url: https://github.com/tmux-plugins/tpm
powerlevel10k:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/romkatv/powerlevel10k
zsh-abbr:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/olets/zsh-abbr
