alias_directories:
  a: ~/ansible
  c: ~/.local/share/chezmoi
  p: ~/powershell
aliases:
  b: bat
  bi: brew install
  bui: brew uninstall
  cat: bat
  caa: chezmoi apply
  ci: choco install
  cr: chezmoi re-add
  cs: choco search
  cu: choco uninstall
  g: git
  j: just
  jd: just dev
  l: lsd
  la: lsd -a
  ll: lsd -l
  lla: lsd -la
  lg: lazygit
  n: nvim
  nr: sh -c "printf \"\e[6 q\"; node"
  p: pnpm
  pd: pnpm dev
  pi: pnpm i
  pp: psql postgresql://postgres:postgres@localhost:5432/postgres
  ppg: pnpm prisma generate
  pr: gh pr create -f
  prm: pnpm rm
  prr: gh pr create -f -r
  rg: rg --max-columns 1000
  scc: scc --not-match "package-lock.json|pnpm-lock.yaml"
  si: scoop install
  ss: scoop search
  su: scoop uninstall
  tg: topgrade
  tns: tmux new-session -A -s
  tsx: pnpm tsx
  tsxr: sh -c 'printf "\e[6 q"; pnpm tsx'
  vim: nvim
  wi: winget install
  ws: winget search
  wu: winget uninstall
functions:
  wcss:
    body:
      - winget search $package
      - choco search $package
      - scoop search $package
    parameters:
      - package
git_aliases:
  aa: add -A
  c: clone
  ca: commit --amend
  cam: commit -a -m
  cm: commit -m
  co: checkout
  d: diff
  l: lg
  lp: lg --patch
  P: push
  p: pull
  r: rebase
  rbc: rebase --continue
  rhh: reset --hard HEAD
  s: s
  sa: stash apply
  sP: stash push
  sp: stash pop
