alias_directories:
  a: ~/ansible
  c: ~/.local/share/chezmoi
  p: ~/powershell
aliases:
  b: bat
  bi: brew install
  bui: brew uninstall
  cat: bat
  ca: chezmoi apply $(sh -c "chezmoi managed --include files --path-style absolute | rg --invert-match '.aws/credentials|.config/ghorg/conf.yaml|.msmtprc'")
  caa: chezmoi apply
  cr: chezmoi re-add
  cu: chezmoi update --exclude templates && chezmoi apply $(sh -c "chezmoi managed --include files --path-style absolute | rg --invert-match '.aws/credentials|.config/ghorg/conf.yaml|.msmtprc'")
  g: git
  j: just
  jd: just dev
  lg: lazygit
  man: batman
  n: nvim
  nr: sh -c "printf \"\e[6 q\"; node"
  os: set COMMAND $(op signin) && test -n "$COMMAND" && eval $COMMAND && set --export OP_TIME $(date +%s)
  p: pnpm
  pd: pnpm dev
  pi: pnpm i
  pp: psql postgresql://postgres:postgres@localhost:5432/postgres
  ppg: pnpm prisma generate
  pr: gh pr create -f
  prm: pnpm rm
  prr: gh pr create -f -r
  rg: rg --max-columns 1000
  scc: scc --not-match "package-lock.json|pnpm-lock.yaml"
  tg: topgrade
  tns: tmux new-session -A -s
  tsx: pnpm tsx
  tsxr: sh -c 'printf "\e[6 q"; pnpm tsx'
  vim: nvim
git_aliases:
  aa: add -A
  c: clone
  ca: commit --amend
  cam: commit -a -m
  cm: commit -m
  co: checkout
  d: diff
  l: lg
  lp: lg --patch
  P: push
  p: pull
  r: rebase
  rbc: rebase --continue
  rhh: reset --hard HEAD
  s: s
  sa: stash apply
  sP: stash push
  sp: stash pop
