.tmux/plugins/tpm:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/tmux-plugins/tpm
enhancd:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/b4b4r07/enhancd
powerlevel10k:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/romkatv/powerlevel10k
zsh-abbr:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/olets/zsh-abbr
zsh-vi-mode:
  refreshPeriod: 168h
  type: git-repo
  url: https://github.com/jeffreytse/zsh-vi-mode
