#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
[ "$PS1" = "" ] && return

HISTCONTROL=ignoreboth
HISTFILESIZE=
HISTSIZE=

shopt -s globstar
shopt -s histappend

source ~/.config/bash/generated.sh
source /usr/share/bash-completion/bash_completion
