# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Finkitd.o.o.ManicTimeServer
PackageVersion: 23.3.1.1
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{110013C5-52EF-40E2-9A0E-279B85062D15}'
Installers:
- InstallerUrl: https://cdn.manictime.com/setup/server/v2023_3_1_1/manictimeserver-setup-2023.3.1.1-win-x64.msi
  Architecture: x64
  InstallerSha256: D1562C664F6CD6E056665F5A0AD35A9E19A13A7163725533D63E0CD10DDD6000
ManifestType: installer
ManifestVersion: 1.5.0
