prSections:
  - title: Open
    filters: is:open author:@me
  - title: Closed
    filters: is:closed author:@me
  - title: Needs My Review
    filters: is:open user-review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: Open
    filters: is:open author:@me
  - title: Closed
    filters: is:closed author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 1
keybindings:
  issues: []
  prs:
    - key: D
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}} &&
        TERM=wezterm nvim -c ":DiffviewOpen $(git default-branch)...{{.HeadRefName}}"
    - key: n
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}} &&
        TERM=wezterm nvim
repoPaths:
  supabase/*: ~/supabase/*
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: delta --pager 'env LESS=--RAW-CONTROL-CHARS less'
