prSections:
  - title: Backend Review Requested
    filters: -author:@me is:open team-review-requested:supabase/backend
  - title: Open
    filters: is:open author:@me user:supabase
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Closed
    filters: is:closed author:@me
issuesSections:
  - title: Open
    filters: is:open author:@me
  - title: Closed
    filters: is:closed author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 5
keybindings:
  issues: []
  prs:
    - key: p
      command: >
        gh pr review {{.PrNumber}} --approve --repo {{.RepoName}}
    - key: D
      command: >
        cd {{.RepoPath}} &&
        git fetch &&
        nvim -c ":DiffviewOpen origin/$(gh api repos/{{.RepoName}}/pulls/{{.PrNumber}} --jq .base.ref)...origin/{{.HeadRefName}}"
    - key: n
      command: >
        cd {{.RepoPath}} &&
        gh pr checkout {{.PrNumber}} &&
        nvim
repoPaths:
  supabase/*: ~/supabase/*
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: delta --pager 'env LESS=--RAW-CONTROL-CHARS less'
