#!/usr/bin/env sh
sudo apt --assume-yes install \
  composer \
  dos2unix \
  ffmpegthumbnailer \
  google-cloud-cli \
  helix \
  libcurl4-openssl-dev \
  libluajit-5.1-dev \
  libpq-dev \
  libsqlite3-dev \
  libxcb-render0-dev \
  libxcb-shape0-dev \
  libxcb-xfixes0-dev \
  lua5.4 \
  make \
  moreutils \
  mosh \
  mosquitto-clients \
  msmtp-mta \
  pass \
  poppler-utils \
  ncat \
  ntpdate \
  parallel \
  php-bcmath \
  php-curl \
  php-gmp \
  speedtest \
  sqlite3 \
  stripe \
  trash-cli \
  unar \
  zsh
