# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Finkitd.o.o.ManicTimeServer
PackageVersion: 23.3.4.0
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{1BC08EA1-CC3D-4443-9524-11C00E841E71}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.manictime.com/setup/server/v2023_3_4_0/manictimeserver-setup-2023.3.4.0-win-x64.msi
  InstallerSha256: 57F44F1728EE62088E74786AF64616E11293175E8B4E92789BB0A4A3C8CC0964
ManifestType: installer
ManifestVersion: 1.5.0
