[commands]
corepack = "corepack prepare pnpm@latest --activate"
gup = "gup update --exclude ghorg"
[misc]
assume_yes = true
disable = ["containers", "go", "vim"]
no_retry = true
[npm]
use_sudo = true
