[commands]
corepack = "corepack prepare pnpm@latest --activate"
just_fish_completions = "just --completions fish > $HOME/.config/fish/completions/just.fish"
[misc]
assume_yes = true
disable = ["vim"]
no_retry = true
[npm]
use_sudo = true
[windows]
enable_winget = true
