[commands]
atuin_fish_completions = "atuin gen-completions --out-dir $HOME/.config/fish/completions --shell fish"
just_fish_completions = "just --completions fish > $HOME/.config/fish/completions/just.fish"
[misc]
assume_yes = true
disable = ["vim"]
[npm]
use_sudo = true
[windows]
enable_winget = true
