- community.general.sudoers:
    commands: ALL
    name: "{{ user }}"
    user: "{{ user }}"
- ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
- ansible.builtin.apt_repository:
    repo: ppa:kelleyk/emacs
- ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
- ansible.builtin.apt_repository:
    repo: ppa:longsleep/golang-backports
- ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
- ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
- ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- ansible.builtin.apt_repository:
    repo: deb https://deb.nodesource.com/node_19.x jammy main
- ansible.builtin.apt_repository:
    repo: deb-src https://deb.nodesource.com/node_19.x jammy main
- ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
- ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main
- ansible.builtin.apt:
    name:
    - awscli
    - containerd.io
    - cargo
    - cmake
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
    - emacs28-nativecomp
    - fish
    - golang
    - google-chrome-stable
    - make
    - mosh
    - nodejs
    - pipx
    - postgresql-client
    - ripgrep
    - unzip
    - xfce4
    - xrdp
    update_cache: yes
- ansible.builtin.apt:
    deb: https://github.com/twpayne/chezmoi/releases/download/v2.26.0/chezmoi_2.26.0_linux_amd64.deb
- ansible.builtin.group:
    name: docker
- ansible.builtin.user:
    append: yes
    groups: docker
    name: "{{ user }}"
    shell: /usr/bin/fish
