- ansible.builtin.command:
    cmd: chezmoi init --apply --ssh thebengeu
    creates: ~/.local/share/chezmoi
- ansible.builtin.command:
    cmd: go install github.com/jesseduffield/lazygit@latest
    creates: ~/go/bin/lazygit
