- ansible.builtin.shell:
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    creates: ~/.config/fish/functions/fisher.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: yes | fisher install IlanCosman/tide@v5
    creates: ~/.config/fish/functions/tide.fish
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: fisher install catppuccin/fish
    creates: ~/.config/fish/themes/Catppuccin Mocha.theme
    executable: /usr/bin/fish
- ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    creates: /home/linuxbrew
- community.general.homebrew:
    name:
      - bat
      - broot
      - btop
      - cantino/mcfly/mcfly
      - emacs
      - eth-p/software/bat-extras-batman
      - fd
      - fnm
      - fzf
      - gh
      - ghorg
      - git-delta
      - gitui
      - lazydocker
      - lazygit
      - neovim
      - mosh
      - topgrade
      - wakatime-cli
      - xh
      - zoxide
- ansible.builtin.git:
    repo: https://github.com/plexus/chemacs2
    dest: ~/.emacs.d
- ansible.builtin.git:
    repo: https://github.com/doomemacs/doomemacs
    dest: ~/doomemacs
- ansible.builtin.git:
    repo: https://git.savannah.gnu.org/git/emacs.git
    dest: ~/emacs
- ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: ~/nerd-fonts
- ansible.builtin.git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/spacemacs
- ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
- ansible.builtin.command:
    cmd: ~/doomemacs/bin/doom install --force --no-fonts
    creates: ~/doomemacs/.local/straight
- ansible.posix.authorized_key:
    key: https://github.com/thebengeu.keys
    user: "{{ user }}"
- community.general.pipx:
    name: tusker
- ansible.builtin.command:
    cmd: chezmoi init --apply --ssh thebengeu
    creates: ~/.local/share/chezmoi
- ansible.builtin.command:
    cmd: ~/.tmux/plugins/tpm/bin/install_plugins
    creates: ~/.tmux/plugins/tmux-pain-control
- ansible.builtin.pip:
    name: pynvim
