[tool.ruff]
select = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C4",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "G",
  "I",
  "ICN",
  "ISC",
  "N",
  "PIE",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "PT",
  "PTH",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "TCH",
  "TID",
  "TRY",
  "UP",
]
