git:
  branchPrefix: beng/
  paging:
    externalDiffCommand: difft --color always
  parseEmoji: true
gui:
  authorColors:
    Angelico: green
    Beng Eu: red
    Crispy1975: blue
    Crispy: blue
    Div Arora: yellow
    Jose Ledesma: blue
    Kamil Ogórek: magenta
    Kevin Grüneberg: magenta
    Paul Cioanca: blue
    Tom Gallacher: cyan
    angelico: green
    delgado3d: blue
    dependabot[bot]: black
    divit: blue
    jose-ledesma: blue
    renovate[bot]: black
  branchColorPatterns:
    ^beng/: red
  commitHashLength: 0
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  scrollHeight: 10
  showBottomLine: false
  showNumstatInFilesView: true
  skipDiscardChangeWarning: true
  skipNoStagedFilesWarning: true
  skipRewordInEditorWarning: true
  skipStashWarning: true
  showDivergenceFromBaseBranch: arrowAndNumber
  switchTabsWithPanelJumpKeys: true
notARepository: quit
os:
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      {{ `printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty` }}
    else
      {{ `printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty` }}
    fi
