git:
  branchPrefix: beng/
  paging:
    externalDiffCommand: difft --color always
  parseEmoji: true
gui:
  authorColors:
    Angelico: magenta
    Beng Eu: red
    Crispy1975: cyan
    Crispy: cyan
    Div Arora: magenta
    Hieu: blue
    Jose Ledesma: cyan
    Kamil Ogórek: blue
    Kevin Grüneberg: blue
    Paul Cioanca: cyan
    Pham Hieu: blue
    Tom Gallacher: magenta
    angelico: magenta
    delgado3d: cyan
    dependabot[bot]: black
    divit: cyan
    jose-ledesma: cyan
    phamhieu: blue
    renovate[bot]: black
  branchColorPatterns:
    ^beng/: red
  commitHashLength: 0
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  scrollHeight: 10
  showBottomLine: false
  showNumstatInFilesView: true
  skipDiscardChangeWarning: true
  skipNoStagedFilesWarning: true
  skipRewordInEditorWarning: true
  skipStashWarning: true
  showDivergenceFromBaseBranch: arrowAndNumber
  switchTabsWithPanelJumpKeys: true
notARepository: quit
os:
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      {{ `printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty` }}
    else
      {{ `printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty` }}
    fi
